"""
Evaluate the detector against the hand-labelled message set.

    python evaluate.py                # prints metrics, writes EVAL.md
    python evaluate.py --threshold 0.6
    python evaluate.py --errors       # also list every false positive / negative

The labelled set is split into `dev` (used while writing the rules) and
`test` (held out, never looked at while tuning). Report the test numbers.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path

from screening.detector import DEFAULT_THRESHOLD, VERSION, screen

HERE = Path(__file__).parent
DATA = HERE / "data" / "labelled_messages.jsonl"


def load() -> list[dict]:
    rows = []
    with DATA.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def prf(tp: int, fp: int, fn: int) -> tuple[float, float, float]:
    p = tp / (tp + fp) if tp + fp else 0.0
    r = tp / (tp + fn) if tp + fn else 0.0
    f1 = 2 * p * r / (p + r) if p + r else 0.0
    return p, r, f1


def evaluate(rows: list[dict], threshold: float) -> dict:
    out = {}
    scored = [(row, screen(row["text"], threshold=threshold)) for row in rows]
    for split in ("all", "dev", "test"):
        sub = [(r, s) for r, s in scored if split == "all" or r.get("split") == split]
        tp = sum(1 for r, s in sub if r["label"] == 1 and s.flagged)
        fp = sum(1 for r, s in sub if r["label"] == 0 and s.flagged)
        fn = sum(1 for r, s in sub if r["label"] == 1 and not s.flagged)
        tn = sum(1 for r, s in sub if r["label"] == 0 and not s.flagged)
        p, r_, f1 = prf(tp, fp, fn)
        out[split] = dict(n=len(sub), positives=tp + fn, negatives=fp + tn, tp=tp, fp=fp, fn=fn, tn=tn,
                          precision=p, recall=r_, f1=f1)
    out["errors"] = {
        "false_positives": [dict(id=r["id"], text=r["text"], score=round(s.score, 2), categories=s.categories,
                                 matches=[m.pattern for m in s.matches], split=r.get("split"))
                            for r, s in scored if r["label"] == 0 and s.flagged],
        "false_negatives": [dict(id=r["id"], text=r["text"], score=round(s.score, 2), categories=s.categories,
                                 split=r.get("split"))
                            for r, s in scored if r["label"] == 1 and not s.flagged],
    }
    # Recall by positive tag, so weak spots are visible.
    by_tag: dict[str, list[int]] = {}
    for r, s in scored:
        if r["label"] == 1:
            for tag in r.get("tags", []):
                by_tag.setdefault(tag, []).append(1 if s.flagged else 0)
    out["recall_by_tag"] = {t: (sum(v) / len(v), len(v)) for t, v in sorted(by_tag.items())}
    return out


def sweep(rows: list[dict]) -> list[tuple[float, float, float, float]]:
    res = []
    for t in [0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.7, 0.8]:
        m = evaluate(rows, t)["test"]
        res.append((t, m["precision"], m["recall"], m["f1"]))
    return res


def write_report(rows: list[dict], threshold: float, results: dict, sw: list) -> None:
    lines = [
        "# Screening detector evaluation",
        "",
        f"Detector version `{VERSION}`, threshold **{threshold}**. Generated by `python evaluate.py`.",
        "",
        f"Labelled set: {len(rows)} messages, hand-written and hand-labelled "
        f"({results['all']['positives']} solicitation, {results['all']['negatives']} benign). "
        "`dev` rows were visible while writing the rules; `test` rows were held out. "
        "Report the `test` row.",
        "",
        "| split | n | precision | recall | F1 | TP | FP | FN | TN |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for split in ("test", "dev", "all"):
        m = results[split]
        lines.append(f"| {split} | {m['n']} | {m['precision']:.3f} | {m['recall']:.3f} | {m['f1']:.3f} | "
                     f"{m['tp']} | {m['fp']} | {m['fn']} | {m['tn']} |")
    lines += ["", "## Threshold sweep (test split)", "", "| threshold | precision | recall | F1 |", "|---|---|---|---|"]
    for t, p, r, f1 in sw:
        mark = " **(chosen)**" if abs(t - threshold) < 1e-9 else ""
        lines.append(f"| {t}{mark} | {p:.3f} | {r:.3f} | {f1:.3f} |")
    lines += ["", "## Recall by positive tag (all rows)", "", "| tag | recall | n |", "|---|---|---|"]
    for tag, (rec, n) in results["recall_by_tag"].items():
        lines.append(f"| {tag} | {rec:.2f} | {n} |")
    fps = results["errors"]["false_positives"]
    fns = results["errors"]["false_negatives"]
    lines += ["", f"## False positives ({len(fps)})", ""]
    lines += [f"- [{e['split']}] #{e['id']} score {e['score']} {e['categories']}: {e['text']}" for e in fps] or ["- none"]
    lines += ["", f"## False negatives ({len(fns)})", ""]
    lines += [f"- [{e['split']}] #{e['id']} score {e['score']} {e['categories']}: {e['text']}" for e in fns] or ["- none"]
    lines += [
        "",
        "## How to read this",
        "",
        "- A flag creates a report in the admin queue; it never blocks a message. False positives cost reviewer",
        "  minutes, false negatives cost a missed grooming signal, so the threshold is set on the recall side of F1.",
        "- Numbers are on a hand-written set, not production traffic. Expect lower precision on real traffic",
        "  (more varied benign chatter) and re-run this after any rule change.",
        "",
    ]
    (HERE / "EVAL.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--threshold", type=float, default=DEFAULT_THRESHOLD)
    ap.add_argument("--errors", action="store_true")
    ap.add_argument("--no-report", action="store_true")
    args = ap.parse_args()

    rows = load()
    counts = Counter((r.get("split"), r["label"]) for r in rows)
    print(f"{len(rows)} labelled messages; per (split,label): {dict(counts)}")
    results = evaluate(rows, args.threshold)
    for split in ("test", "dev", "all"):
        m = results[split]
        print(f"[{split:4}] n={m['n']:3}  P={m['precision']:.3f}  R={m['recall']:.3f}  F1={m['f1']:.3f}  "
              f"TP={m['tp']} FP={m['fp']} FN={m['fn']} TN={m['tn']}")
    sw = sweep(rows)
    print("threshold sweep (test):", "  ".join(f"{t}:P{p:.2f}/R{r:.2f}" for t, p, r, _ in sw))
    if args.errors:
        print("\nFALSE POSITIVES")
        for e in results["errors"]["false_positives"]:
            print(f"  [{e['split']}] #{e['id']} {e['score']} {e['matches']} :: {e['text']}")
        print("\nFALSE NEGATIVES")
        for e in results["errors"]["false_negatives"]:
            print(f"  [{e['split']}] #{e['id']} {e['score']} {e['categories']} :: {e['text']}")
    if not args.no_report:
        write_report(rows, args.threshold, results, sw)
        print("wrote EVAL.md")


if __name__ == "__main__":
    main()
